python3 trainer/main_continual.py \
    --dataset ntu60 \
    --encoder stgcn \
    --data_dir ./data/ntu60/xsub \
    --split_strategy class \
    --encoder stgcn \
    --pooling_mode part \
    --task_split_key NTU60_xsub \
    --hidden_channels 64 \
    --max_epochs 500 \
    --num_tasks 5 \
    --task_idx 1 \
    --gpus 0 \
    --precision 16 \
    --optimizer sgd \
    --lars \
    --grad_clip_lars \
    --eta_lars 0.02 \
    --exclude_bias_n_norm \
    --scheduler warmup_cosine \
    --lr 0.1 \
    --classifier_lr 0.01 \
    --weight_decay 1e-5 \
    --batch_size 128 \
    --num_workers 5 \
    --name PIECED \
    --project PIECED_ntu60_xsub \
    --wandb \
    --save_checkpoint \
    --method byol \
    --output_dim 256 \
    --proj_hidden_dim 4096 \
    --base_tau_momentum 0.99 \
    --final_tau_momentum 1.0 \
    --momentum_classifier \
    --distiller predictive \
    --pretrained_model exp/ntu60_xsub/<run_id>/FT-task0-ep=499-<hash>.ckpt \
    --distill_lamb 1.0 \
    --seed 5 \
    --attention_mode transformer